name: flutter_myinsta
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.5+3
  flutter_icons:
  cached_network_image: ^3.2.1
  fluttertoast: ^8.0.9
  shared_preferences: ^2.0.15
  firebase_core: ^1.20.0
  firebase_auth: ^3.6.2
  firebase_storage: ^10.3.4
  cloud_firestore: ^3.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf